IF OBJECT_ID('BRONZE.CRM_CUST_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_CUST_INFO
CREATE TABLE BRONZE.CRM_CUST_INFO(
cst_id INT,
cst_key NVARCHAR(50),
cst_firstname NVARCHAR(50),
cst_lastname NVARCHAR(50),
cst_material_status NVARCHAR(50),
cst_gndr NVARCHAR(20),
cst_create_date DATE
);

IF OBJECT_ID('BRONZE.CRM_PRD_INFO','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_PRD_INFO
CREATE TABLE BRONZE.CRM_PRD_INFO(
prd_id INT,
prd_key NVARCHAR(50),
prd_nm NVARCHAR(50),
prd_cost INT,
prd_line NVARCHAR(50),
prd_start_dt DATE,
prd_end_dt DATE
);


IF OBJECT_ID('BRONZE.CRM_sales_details','U') IS NOT NULL
	DROP TABLE BRONZE.CRM_sales_details
CREATE TABLE BRONZE.CRM_sales_details(
sls_ord_num NVARCHAR(50),
sls_prd_key NVARCHAR(50),
sls_cust_id INT,
sls_order_dt INT,
sls_ship_dt INT,
sls_due_dt INT,
sls_sales INT,
sls_quantity INT,
sls_price INT
);

IF OBJECT_ID('BRONZE.ERP_CUSTAZ12','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUSTAZ12
CREATE TABLE BRONZE.ERP_CUSTAZ12(
CID NVARCHAR(50),
BDATE DATE,
GEN NVARCHAR(50)
);

IF OBJECT_ID('BRONZE.ERP_LOC_A101','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_LOC_A101
CREATE TABLE BRONZE.ERP_LOC_A101(
CID NVARCHAR(50),
CNTRY NVARCHAR(50)
);


IF OBJECT_ID('BRONZE.ERP_PX_CAT_G1V2','U') IS NOT NULL
	DROP TABLE BRONZE.ERP_PX_CAT_G1V2
CREATE TABLE BRONZE.ERP_PX_CAT_G1V2(
ID NVARCHAR(50),
CAT NVARCHAR(50),
SUBCAT NVARCHAR(50),
MAINTENANCE NVARCHAR(50)
);

CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN

TRUNCATE TABLE BRONZE.CRM_CUST_INFO;
BULK INSERT BRONZE.CRM_CUST_INFO
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\cust_info.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.CRM_CUST_INFO;
SELECT COUNT(*) FROM BRONZE.CRM_CUST_INFO;

TRUNCATE TABLE BRONZE.CRM_PRD_INFO;
BULK INSERT BRONZE.CRM_PRD_INFO
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\prd_info.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );


SELECT * FROM BRONZE.CRM_PRD_INFO;
SELECT COUNT(*) FROM BRONZE.CRM_PRD_INFO;

TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS;
BULK INSERT BRONZE.CRM_SALES_DETAILS
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\sales_details.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );


SELECT * FROM BRONZE.CRM_SALES_DETAILS;
SELECT COUNT(*) FROM BRONZE.CRM_SALES_DETAILS;


TRUNCATE TABLE BRONZE.ERP_CUSTAZ12;
BULK INSERT BRONZE.ERP_CUSTAZ12
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\CUST_AZ12.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_CUSTAZ12;
SELECT COUNT(*) FROM BRONZE.ERP_CUSTAZ12;


TRUNCATE TABLE BRONZE.ERP_LOC_A101;
BULK INSERT BRONZE.ERP_LOC_A101
FROM'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\LOC_A101.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_LOC_A101;
SELECT COUNT(*) FROM BRONZE.ERP_LOC_A101;

TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2;
BULK INSERT BRONZE.ERP_PX_CAT_G1V2
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\PX_CAT_G1V2.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_PX_CAT_G1V2;
SELECT COUNT(*) FROM BRONZE.ERP_PX_CAT_G1V2;
END;
