CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN

TRUNCATE TABLE BRONZE.CRM_CUST_INFO;
BULK INSERT BRONZE.CRM_CUST_INFO
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\cust_info.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.CRM_CUST_INFO;
SELECT COUNT(*) FROM BRONZE.CRM_CUST_INFO;

TRUNCATE TABLE BRONZE.CRM_PRD_INFO;
BULK INSERT BRONZE.CRM_PRD_INFO
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\prd_info.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );


SELECT * FROM BRONZE.CRM_PRD_INFO;
SELECT COUNT(*) FROM BRONZE.CRM_PRD_INFO;

TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS;
BULK INSERT BRONZE.CRM_SALES_DETAILS
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_crm\sales_details.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );


SELECT * FROM BRONZE.CRM_SALES_DETAILS;
SELECT COUNT(*) FROM BRONZE.CRM_SALES_DETAILS;


TRUNCATE TABLE BRONZE.ERP_CUSTAZ12;
BULK INSERT BRONZE.ERP_CUSTAZ12
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\CUST_AZ12.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_CUSTAZ12;
SELECT COUNT(*) FROM BRONZE.ERP_CUSTAZ12;


TRUNCATE TABLE BRONZE.ERP_LOC_A101;
BULK INSERT BRONZE.ERP_LOC_A101
FROM'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\LOC_A101.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_LOC_A101;
SELECT COUNT(*) FROM BRONZE.ERP_LOC_A101;

TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2;
BULK INSERT BRONZE.ERP_PX_CAT_G1V2
FROM 'C:\Users\zakir\Downloads\dbc9660c89a3480fa5eb9bae464d6c07\sql-data-warehouse-project\datasets\source_erp\PX_CAT_G1V2.csv'
WITH(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	TABLOCK
		    );

SELECT * FROM BRONZE.ERP_PX_CAT_G1V2;
SELECT COUNT(*) FROM BRONZE.ERP_PX_CAT_G1V2;
END;
